/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JAF;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Megi
 */
public class signup extends javax.swing.JPanel {

    /**
     * Creates new form sig_up
     */
    public signup() {
        initComponents();
        position_btn();
        update_btn.setVisible(false);
        delete_btn.setVisible(false);
         create_btn.setVisible(true);
    }
    String Sex;
    String Position;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        useremailinput = new javax.swing.JTextField();
        userpassinput = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        create_btn = new javax.swing.JButton();
        cancel_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        userphoneinput = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        position = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        male = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        usernameinput = new javax.swing.JTextField();
        delete_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        search = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(25, 150, 130));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        useremailinput.setBackground(new java.awt.Color(25, 150, 130));
        useremailinput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        useremailinput.setForeground(new java.awt.Color(255, 255, 255));
        useremailinput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        useremailinput.setCaretColor(new java.awt.Color(255, 153, 204));
        useremailinput.setOpaque(false);
        jPanel1.add(useremailinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 240, 40));

        userpassinput.setBackground(new java.awt.Color(25, 150, 130));
        userpassinput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userpassinput.setForeground(new java.awt.Color(255, 255, 255));
        userpassinput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        userpassinput.setOpaque(false);
        userpassinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userpassinputActionPerformed(evt);
            }
        });
        jPanel1.add(userpassinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 240, 30));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 110, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 80, 30));

        create_btn.setBackground(new java.awt.Color(102, 102, 102));
        create_btn.setForeground(new java.awt.Color(255, 255, 255));
        create_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_add_26px_1.png"))); // NOI18N
        create_btn.setText("create");
        create_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create_btnActionPerformed(evt);
            }
        });
        jPanel1.add(create_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 580, 140, 40));

        cancel_btn.setBackground(new java.awt.Color(102, 102, 102));
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_cancel_26px.png"))); // NOI18N
        cancel_btn.setText("cancel");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 580, 140, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_user_100px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 100, 90));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, 30));

        userphoneinput.setBackground(new java.awt.Color(25, 150, 130));
        userphoneinput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        userphoneinput.setForeground(new java.awt.Color(255, 255, 255));
        userphoneinput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        userphoneinput.setCaretColor(new java.awt.Color(255, 153, 204));
        userphoneinput.setOpaque(false);
        jPanel1.add(userphoneinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 240, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign Up");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 110, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Phone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 80, 30));

        position.setBackground(new java.awt.Color(25, 150, 130));
        position.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        position.setForeground(new java.awt.Color(255, 255, 255));
        position.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 255)));
        position.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        position.setOpaque(false);
        position.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                positionItemStateChanged(evt);
            }
        });
        position.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                positionPropertyChange(evt);
            }
        });
        jPanel1.add(position, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 260, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("User Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 80, 30));

        female.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(female);
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));

        male.setBackground(new java.awt.Color(102, 102, 102));
        buttonGroup1.add(male);
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sex");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 80, 30));

        usernameinput.setBackground(new java.awt.Color(25, 150, 130));
        usernameinput.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        usernameinput.setForeground(new java.awt.Color(255, 255, 255));
        usernameinput.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        usernameinput.setCaretColor(new java.awt.Color(255, 153, 204));
        usernameinput.setOpaque(false);
        jPanel1.add(usernameinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 240, 40));

        delete_btn.setBackground(new java.awt.Color(102, 102, 102));
        delete_btn.setForeground(new java.awt.Color(255, 255, 255));
        delete_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_trash_26px.png"))); // NOI18N
        delete_btn.setText("Delete");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, 140, 40));

        update_btn.setBackground(new java.awt.Color(102, 102, 102));
        update_btn.setForeground(new java.awt.Color(255, 255, 255));
        update_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_update_left_rotation_26px.png"))); // NOI18N
        update_btn.setText("Update");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 580, 140, 40));

        search.setBackground(new java.awt.Color(25, 150, 130));
        search.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        search.setCaretColor(new java.awt.Color(255, 153, 204));
        search.setOpaque(false);
        search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchKeyTyped(evt);
            }
        });
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 240, 40));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_search_50px_1.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, 70, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void position_btn(){
             try {
           Statement s = database.mycon().createStatement();
            ResultSet rs=s.executeQuery("select * from position");
                while(rs.next()){
                    String Waitres=rs.getString("position");
                    position.addItem(Waitres);
                }
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
      public void check_username(){
      String User_Name=usernameinput.getText();
      try{
          Statement s = database.mycon().createStatement();
          ResultSet rs = s.executeQuery("SELECT * FROM user username ='"+User_Name+"'");
          while(rs.next()){
              String username;
              username=rs.getString("username");
              if(User_Name==username){
                    JOptionPane.showMessageDialog(this, "username already exixst use another !");
              }else{
                   CreateAccount(); 
              }
          }
      }catch(Exception e){
          
      }
      
          
  }
      public void CreateAccount(){
           String UserName =  usernameinput.getText();   // User Name
        
        
        if(male.isSelected()){
            Sex = "Male";
        }
        if(female.isSelected()){
            Sex = "Female";
        }
        String Password = userpassinput.getText();
        String UserPhone = userphoneinput.getText();
        String UserEmail = useremailinput.getText();
        Position=position.getSelectedItem().toString();
      if(UserName.equals("")){
          JOptionPane.showMessageDialog(null, "Please enter user name");
      }else if(Password.equals("")){
          JOptionPane.showMessageDialog(null, "Please enter Password");
      }else if(UserPhone.equals("")){
          JOptionPane.showMessageDialog(null, "Please enter user phone");
      }else if(UserEmail.equals("")){
          JOptionPane.showMessageDialog(null, "Please enter user email");
      }else if(UserName.equals("")&& Password.equals("") && UserPhone.equals("") && UserEmail.equals("") && Sex.equals("")){
          JOptionPane.showMessageDialog(null, "Please enter fields correctly");
      }else{
          
      

        try {
            Statement s = database.mycon().createStatement();  // calling the database class and mycon() constructor.
            s.executeUpdate("INSERT INTO user (username,usersex,userpass,userphone,useremail,position) VALUES('"+UserName+"','"+Sex+"','"+Password+"','"+UserPhone+"','"+UserEmail+"','"+Position+"')");
            // SQL syntax to add the data to the database
            JOptionPane.showMessageDialog(null, "User Account Created !");  // to show that the item is added.
            Dashboard db = new Dashboard();   // getting to the dash-board
            db.setVisible(true);  // making visible the dash-board GUI
            //this.dispose();    // this closes the current class GUI

        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
      }
    private void userpassinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userpassinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userpassinputActionPerformed

    private void create_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create_btnActionPerformed
        // accepting user inputs from the labels as form of String values
       CreateAccount();
    }//GEN-LAST:event_create_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        usernameinput.setText("");
        buttonGroup1.clearSelection();
        useremailinput.setText("");
        userpassinput.setText("");
        userphoneinput.setText("");
        position.setSelectedIndex(0);
        search.setText("");
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void positionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_positionItemStateChanged

    }//GEN-LAST:event_positionItemStateChanged

    private void positionPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_positionPropertyChange

    }//GEN-LAST:event_positionPropertyChange

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TO delete the user data from the database.
          int x = JOptionPane.showConfirmDialog(null, "Do you Want To delet this! ?", "Delete User",JOptionPane.YES_NO_OPTION);
       if(x==0){
        String Search = search.getText();
        try{
            Statement s = database.mycon().createStatement();
            s.executeUpdate("DELETE FROM user WHERE id = '"+Search+"'");
          usernameinput.setText("");
        buttonGroup1.clearSelection();
        useremailinput.setText("");
        userpassinput.setText("");
        userphoneinput.setText("");
        search.setText("");
        position.setSelectedIndex(0);
            delete_btn.setVisible(false);
                   update_btn.setVisible(false);
                   create_btn.setVisible(true);
        }catch(Exception e){
              System.out.print(e);
        }
       }
    }//GEN-LAST:event_delete_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // update the data
          int x = JOptionPane.showConfirmDialog(null, "Do you Want To Update this! ?", "Update user",JOptionPane.YES_NO_OPTION);
       if(x==0){
        String Searchkey = search.getText();
        String User_Name = usernameinput.getText();
     
        if(male.isSelected()){
            Sex="Male";
        }if(female.isSelected()){
            Sex="Female";
        }
        String User_Password = userpassinput.getText();
        String User_Email = useremailinput.getText();
        String User_Phone = userphoneinput.getText();
         Position=position.getSelectedItem().toString();
         try{
             Statement s = database.mycon().createStatement();
             s.executeUpdate("UPDATE user SET username ='"+User_Name+"',usersex ='"+Sex+"',userpass ='"+User_Password+"',userphone ='"+User_Phone+"',useremail ='"+User_Email+"',position ='"+Position+"' WHERE id = '"+Searchkey+"'");
         usernameinput.setText("");
        buttonGroup1.clearSelection();
        useremailinput.setText("");
        userpassinput.setText("");
        userphoneinput.setText("");
         search.setText("");
        position.setSelectedIndex(0);
            delete_btn.setVisible(false);
                   update_btn.setVisible(false);
                   create_btn.setVisible(true);
        
         }catch(Exception e){
             System.out.print(e);
             
         }
       }
        
    }//GEN-LAST:event_update_btnActionPerformed

    private void searchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyPressed
        // To search vales
    /*    String Search = search.getText();
        try {
            Statement stmt=database.mycon().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM user WHERE id = '"+Search+"'");
            if(rs.next()){
                usernameinput.setText(rs.getString("username"));
                buttonGroup1.equals(rs.getString("usersex"));
               String Sexx = rs.getString("usersex");
                   if(Sexx.equals("Male")){
                       male.setSelected(true);
                   }
                    else if(Sexx.equals("Female")){
                       female.setSelected(true);
                   }else{
                        buttonGroup1.clearSelection();
                       JOptionPane.showMessageDialog(this, "no sex information");
                     
                   }
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
*/
    }//GEN-LAST:event_searchKeyPressed

    private void searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchKeyTyped
        // 
          String Search = search.getText();
        try {
            Statement stmt=database.mycon().createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM user WHERE id = '"+Search+"'");
            if(rs.next()){
                usernameinput.setText(rs.getString("username"));
                buttonGroup1.equals(rs.getString("usersex"));
               String Sexx = rs.getString("usersex");
                   if(Sexx.equals("Male")){
                       male.setSelected(true);
                   }
                   else if(Sexx.equals("Female")){
                       female.setSelected(true);
                   }else {
                        buttonGroup1.clearSelection();
                       JOptionPane.showMessageDialog(null, "no sex information");
                     
                   }
                  userpassinput.setText(rs.getString("userpass"));
                  userphoneinput.setText(rs.getString("userphone"));
                  useremailinput.setText(rs.getString("useremail"));
                  
                  
            }
        } catch (SQLException ex) {
            Logger.getLogger(signup.class.getName()).log(Level.SEVERE, null, ex);
        }
               if(Search.equals("")){
                    usernameinput.setText("");
        buttonGroup1.clearSelection();
        useremailinput.setText("");
        userpassinput.setText("");
        userphoneinput.setText("");
        position.setSelectedIndex(0);
                   delete_btn.setVisible(false);
                   update_btn.setVisible(false);
                   create_btn.setVisible(true);
               }else if(!Search.equals("")){
                   create_btn.setVisible(false);
                    delete_btn.setVisible(true);
                   update_btn.setVisible(true); 
               }
    }//GEN-LAST:event_searchKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton create_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton male;
    private javax.swing.JComboBox<String> position;
    private javax.swing.JTextField search;
    private javax.swing.JButton update_btn;
    private javax.swing.JTextField useremailinput;
    private javax.swing.JTextField usernameinput;
    private javax.swing.JPasswordField userpassinput;
    private javax.swing.JTextField userphoneinput;
    // End of variables declaration//GEN-END:variables
}
